In [1]:
import numpy as np
from numpy import linalg as la

In [7]:
x0 = np.array([1,2,1,1,1,0,0,0,2,3,5,6,4,5,3,2,1,2,3,8,1,2,1,1,1,0,0,0,2,3,5,6,4,5,3,2,1,2,3,8]).reshape([-1,8])
print (x0)

[[1 2 1 1 1 0 0 0]
 [2 3 5 6 4 5 3 2]
 [1 2 3 8 1 2 1 1]
 [1 0 0 0 2 3 5 6]
 [4 5 3 2 1 2 3 8]]


In [9]:
print(x0[0]) #row

[1 2 1 1 1 0 0 0]


In [10]:
print(x0[:,0]) #column

[1 2 1 1 4]


In [11]:
print(x0.T[0]) #column

[1 2 1 1 4]


In [16]:
num_rows = (len(x0))
print("rows: " + str(num_rows))
num_columns = (len(x0[0]))
print("columns: " + str(num_columns) )
print(str(num_rows)+"x"+str(num_columns)+" matrix")

rows: 5
columns: 8
5x8 matrix


In [35]:
x1 = np.array([[x0[0][0], x0[0][1]],[x0[1][0], x0[1][1]]]) # 'bigram'
print(x1)

[[1 2]
 [2 3]]


In [39]:
for i in range(0, num_rows-1):
    tempx = np.array([[x0[i][0],x0[i][1]],[x0[i+1][0],x0[i+1][1]]])
    print(tempx)
    print("------")
       

[[1 2]
 [2 3]]
------
[[2 3]
 [1 2]]
------
[[1 2]
 [1 0]]
------
[[1 0]
 [4 5]]
------
