In [1]:
import numpy as np
import time

In [2]:
x0 = np.random.randint(9, size=(12, 13))
print(x0)

[[7 7 7 5 5 0 4 1 7 3 0 3 1]
 [0 1 8 4 2 1 8 3 6 7 6 1 8]
 [3 8 2 8 8 1 5 7 8 2 0 0 3]
 [5 5 3 5 6 8 2 5 3 8 4 8 4]
 [6 2 6 5 1 5 4 2 5 5 8 1 2]
 [2 6 1 5 2 8 1 5 6 2 1 4 4]
 [0 0 7 3 3 1 4 6 4 6 7 6 4]
 [8 8 6 1 2 1 5 6 0 7 6 0 2]
 [7 4 5 5 5 6 6 3 3 1 8 7 1]
 [0 5 0 7 3 5 3 7 4 5 1 4 1]
 [4 3 7 1 7 1 6 0 3 8 3 1 3]
 [5 8 4 2 4 4 2 7 2 1 1 1 6]]


In [3]:
print(x0[0]) #row

[7 7 7 5 5 0 4 1 7 3 0 3 1]


In [4]:
print(x0[:,0]) #column
print(x0.T[0]) #column

[7 0 3 5 6 2 0 8 7 0 4 5]
[7 0 3 5 6 2 0 8 7 0 4 5]


In [5]:
num_rows = (len(x0))
num_columns = (len(x0[0]))
print("x0 is a "+str(num_rows)+"x"+str(num_columns)+" matrix")

x0 is a 12x13 matrix


In [6]:
x1 = np.array([[x0[0][0], x0[0][1]],[x0[1][0], x0[1][1]]]) # 'bigram'
print(x1)

[[7 7]
 [0 1]]


In [7]:
'''Moves down the matrix from upper left corner'''

def matrixNgram(matrix, n):
    num_rows = (len(matrix))
    num_columns = (len(matrix[0]))
    print(str(num_rows)+"x"+str(num_columns)+" matrix")
    for i in range(0, num_rows):
        print("Row " + str(i))
        temp_list_of_rows = []
        
        gram_rows = np.array(matrix[i:(i+n)]) #make matricies with sliding window of 3 rows
        if len(gram_rows) == n:
#             print(gram_rows)
#             print("------")

            for j in range(0, n): #shorten num of gram_row columns to n, 
                temp_row = gram_rows[j][:n]
                temp_list_of_rows.append(temp_row)
                
            gram = np.array(temp_list_of_rows)
            print(gram)
            print("-------------")
        if len(gram_rows) < n:
            print("not enough rows to compute")

            

print(x0)
matrixNgram(x0, 4)    

[[7 7 7 5 5 0 4 1 7 3 0 3 1]
 [0 1 8 4 2 1 8 3 6 7 6 1 8]
 [3 8 2 8 8 1 5 7 8 2 0 0 3]
 [5 5 3 5 6 8 2 5 3 8 4 8 4]
 [6 2 6 5 1 5 4 2 5 5 8 1 2]
 [2 6 1 5 2 8 1 5 6 2 1 4 4]
 [0 0 7 3 3 1 4 6 4 6 7 6 4]
 [8 8 6 1 2 1 5 6 0 7 6 0 2]
 [7 4 5 5 5 6 6 3 3 1 8 7 1]
 [0 5 0 7 3 5 3 7 4 5 1 4 1]
 [4 3 7 1 7 1 6 0 3 8 3 1 3]
 [5 8 4 2 4 4 2 7 2 1 1 1 6]]
12x13 matrix
Row 0
[[7 7 7 5]
 [0 1 8 4]
 [3 8 2 8]
 [5 5 3 5]]
-------------
Row 1
[[0 1 8 4]
 [3 8 2 8]
 [5 5 3 5]
 [6 2 6 5]]
-------------
Row 2
[[3 8 2 8]
 [5 5 3 5]
 [6 2 6 5]
 [2 6 1 5]]
-------------
Row 3
[[5 5 3 5]
 [6 2 6 5]
 [2 6 1 5]
 [0 0 7 3]]
-------------
Row 4
[[6 2 6 5]
 [2 6 1 5]
 [0 0 7 3]
 [8 8 6 1]]
-------------
Row 5
[[2 6 1 5]
 [0 0 7 3]
 [8 8 6 1]
 [7 4 5 5]]
-------------
Row 6
[[0 0 7 3]
 [8 8 6 1]
 [7 4 5 5]
 [0 5 0 7]]
-------------
Row 7
[[8 8 6 1]
 [7 4 5 5]
 [0 5 0 7]
 [4 3 7 1]]
-------------
Row 8
[[7 4 5 5]
 [0 5 0 7]
 [4 3 7 1]
 [5 8 4 2]]
-------------
Row 9
not enough rows to compute
Row 10
not enough ro

In [8]:
'''Moves diagonally accross the matrix'''

def matrixNgram2(matrix, n):
    num_rows = (len(matrix))
    num_columns = (len(matrix[0]))
    print(str(num_rows)+"x"+str(num_columns)+" matrix")
    

    c = 0
    for i in range(0, num_rows):
        print("Row " + str(i))
        start_nw = []
        
        west_rows = np.array(matrix[i:(i+n)]) #make running matricies with sliding window of n rows
        if len(west_rows) == n:
#             print(west_rows)
#             print("------")

            for j in range(0, n): #shorten num of gram_row columns to
                temp_row = west_rows[j][c:n+c] #shift columns over each time to move diagonal, with n-gram window
                start_nw.append(temp_row)
                
            start_gram = np.array(start_nw)
            print(start_gram)
            print("-------------")
        if len(west_rows) < n:
            print("not enough rows to compute")
        
        c +=1

print(x0)
matrixNgram2(x0, 4)

[[7 7 7 5 5 0 4 1 7 3 0 3 1]
 [0 1 8 4 2 1 8 3 6 7 6 1 8]
 [3 8 2 8 8 1 5 7 8 2 0 0 3]
 [5 5 3 5 6 8 2 5 3 8 4 8 4]
 [6 2 6 5 1 5 4 2 5 5 8 1 2]
 [2 6 1 5 2 8 1 5 6 2 1 4 4]
 [0 0 7 3 3 1 4 6 4 6 7 6 4]
 [8 8 6 1 2 1 5 6 0 7 6 0 2]
 [7 4 5 5 5 6 6 3 3 1 8 7 1]
 [0 5 0 7 3 5 3 7 4 5 1 4 1]
 [4 3 7 1 7 1 6 0 3 8 3 1 3]
 [5 8 4 2 4 4 2 7 2 1 1 1 6]]
12x13 matrix
Row 0
[[7 7 7 5]
 [0 1 8 4]
 [3 8 2 8]
 [5 5 3 5]]
-------------
Row 1
[[1 8 4 2]
 [8 2 8 8]
 [5 3 5 6]
 [2 6 5 1]]
-------------
Row 2
[[2 8 8 1]
 [3 5 6 8]
 [6 5 1 5]
 [1 5 2 8]]
-------------
Row 3
[[5 6 8 2]
 [5 1 5 4]
 [5 2 8 1]
 [3 3 1 4]]
-------------
Row 4
[[1 5 4 2]
 [2 8 1 5]
 [3 1 4 6]
 [2 1 5 6]]
-------------
Row 5
[[8 1 5 6]
 [1 4 6 4]
 [1 5 6 0]
 [6 6 3 3]]
-------------
Row 6
[[4 6 4 6]
 [5 6 0 7]
 [6 3 3 1]
 [3 7 4 5]]
-------------
Row 7
[[6 0 7 6]
 [3 3 1 8]
 [7 4 5 1]
 [0 3 8 3]]
-------------
Row 8
[[3 1 8 7]
 [4 5 1 4]
 [3 8 3 1]
 [2 1 1 1]]
-------------
Row 9
not enough rows to compute
Row 10
not enough ro

In [9]:
def matrixNgramAll(matrix, n):
    t0 = time.time()
    
    num_rows = (len(matrix))
    num_columns = (len(matrix[0]))
    print(str(num_rows)+"x"+str(num_columns)+" matrix")
    
    ngrams = [] #list of np.array matrix n-grams
    
    #for each column
    for c in range(0, num_columns):
        print("Column " + str(c+1))
        
        #for each row 
        for r in range(0, num_rows):
            print("Row " + str(r+1))
            temp_list_of_rows = []

            gram_rows = np.array(matrix[r:(r+n)]) #make matricies with sliding window of n rows
            if len(gram_rows) == n:
                 #print(gram_rows)
#                 print("------")

                for j in range(0, n): #shorten num of gram_row columns to n, with sliding window of n columns 
                    #array[row][column] 
                    temp_row = gram_rows[j][0+c:n+c] #n rows, :n columns
#                     print("size: " + str(temp_row.size))
#                     print("shape: " + str(temp_row.shape))
                    #only append temp rows of correct column n-gram length
                    if (temp_row.size) == n:
                        temp_list_of_rows.append(temp_row)
                    if (temp_row.size) < n:
                        print("not enough columns to compute")

                gram = np.array(temp_list_of_rows)
                print(gram)
                print("-------------")
                
                #make sure that gram is not an emtpy array (checking temp_row.size doesn't actually help)
                if gram.size == n*n:
                    ngrams.append(gram)
                          
            if len(gram_rows) < n:
                print("not enough rows to compute")
    
    #return list of grams
    print("self info: done in %0.3fs." % (time.time() - t0))
    return ngrams

            
print(x0)
ngrams = matrixNgramAll(x0, 4) #self info: done in 0.053s.

[[7 7 7 5 5 0 4 1 7 3 0 3 1]
 [0 1 8 4 2 1 8 3 6 7 6 1 8]
 [3 8 2 8 8 1 5 7 8 2 0 0 3]
 [5 5 3 5 6 8 2 5 3 8 4 8 4]
 [6 2 6 5 1 5 4 2 5 5 8 1 2]
 [2 6 1 5 2 8 1 5 6 2 1 4 4]
 [0 0 7 3 3 1 4 6 4 6 7 6 4]
 [8 8 6 1 2 1 5 6 0 7 6 0 2]
 [7 4 5 5 5 6 6 3 3 1 8 7 1]
 [0 5 0 7 3 5 3 7 4 5 1 4 1]
 [4 3 7 1 7 1 6 0 3 8 3 1 3]
 [5 8 4 2 4 4 2 7 2 1 1 1 6]]
12x13 matrix
Column 1
Row 1
[[7 7 7 5]
 [0 1 8 4]
 [3 8 2 8]
 [5 5 3 5]]
-------------
Row 2
[[0 1 8 4]
 [3 8 2 8]
 [5 5 3 5]
 [6 2 6 5]]
-------------
Row 3
[[3 8 2 8]
 [5 5 3 5]
 [6 2 6 5]
 [2 6 1 5]]
-------------
Row 4
[[5 5 3 5]
 [6 2 6 5]
 [2 6 1 5]
 [0 0 7 3]]
-------------
Row 5
[[6 2 6 5]
 [2 6 1 5]
 [0 0 7 3]
 [8 8 6 1]]
-------------
Row 6
[[2 6 1 5]
 [0 0 7 3]
 [8 8 6 1]
 [7 4 5 5]]
-------------
Row 7
[[0 0 7 3]
 [8 8 6 1]
 [7 4 5 5]
 [0 5 0 7]]
-------------
Row 8
[[8 8 6 1]
 [7 4 5 5]
 [0 5 0 7]
 [4 3 7 1]]
-------------
Row 9
[[7 4 5 5]
 [0 5 0 7]
 [4 3 7 1]
 [5 8 4 2]]
-------------
Row 10
not enough rows to compute
Row 11
not

In [11]:
#without comments clogging up the function
def matrixNgramAll2(matrix, n):
    t0 = time.time()
    num_rows = (len(matrix))
    num_columns = (len(matrix[0]))
    
    ngrams = [] #list of np.array matrix n-grams
        
    #for each column
    for c in range(0, num_columns):    
        #for each row 
        for r in range(0, num_rows):
            temp_list_of_rows = [] #init empty list for rows 

            gram_rows = np.array(matrix[r:(r+n)]) #make matricies with sliding window of n rows
            if len(gram_rows) == n:
                for j in range(0, n): 
                    temp_row = gram_rows[j][0+c:n+c] #make matricies with sliding window of n columns
                    
                    #only append temp rows of correct column n-gram dimensions 
                    if (temp_row.size) == n:
                        temp_list_of_rows.append(temp_row)

                gram = np.array(temp_list_of_rows)
                if gram.size == n*n:
                    ngrams.append(gram)
                              
    #return list of grams
    print("self info: done in %0.3fs." % (time.time() - t0))
    return ngrams

ngrams2 = matrixNgramAll2(x0, 5)
print(ngrams2)

# Don't do this, this will crash your browser :'(
# x2 = np.random.randint(100, size=(1200, 1300))
# print(ngrams2) 

self info: done in 0.001s.
[array([[7, 7, 7, 5, 5],
       [0, 1, 8, 4, 2],
       [3, 8, 2, 8, 8],
       [5, 5, 3, 5, 6],
       [6, 2, 6, 5, 1]]), array([[0, 1, 8, 4, 2],
       [3, 8, 2, 8, 8],
       [5, 5, 3, 5, 6],
       [6, 2, 6, 5, 1],
       [2, 6, 1, 5, 2]]), array([[3, 8, 2, 8, 8],
       [5, 5, 3, 5, 6],
       [6, 2, 6, 5, 1],
       [2, 6, 1, 5, 2],
       [0, 0, 7, 3, 3]]), array([[5, 5, 3, 5, 6],
       [6, 2, 6, 5, 1],
       [2, 6, 1, 5, 2],
       [0, 0, 7, 3, 3],
       [8, 8, 6, 1, 2]]), array([[6, 2, 6, 5, 1],
       [2, 6, 1, 5, 2],
       [0, 0, 7, 3, 3],
       [8, 8, 6, 1, 2],
       [7, 4, 5, 5, 5]]), array([[2, 6, 1, 5, 2],
       [0, 0, 7, 3, 3],
       [8, 8, 6, 1, 2],
       [7, 4, 5, 5, 5],
       [0, 5, 0, 7, 3]]), array([[0, 0, 7, 3, 3],
       [8, 8, 6, 1, 2],
       [7, 4, 5, 5, 5],
       [0, 5, 0, 7, 3],
       [4, 3, 7, 1, 7]]), array([[8, 8, 6, 1, 2],
       [7, 4, 5, 5, 5],
       [0, 5, 0, 7, 3],
       [4, 3, 7, 1, 7],
       [5, 8, 4, 2, 4]