In [1]:
import numpy as np

In [2]:
x0 = np.random.randint(9, size=(12, 13))
print(x0)

[[0 5 0 3 6 8 1 0 5 7 0 8 5]
 [3 6 5 0 6 7 7 1 6 2 2 2 2]
 [2 2 5 6 4 2 7 1 8 8 6 8 1]
 [6 3 7 4 4 3 1 4 5 6 0 3 4]
 [6 6 0 8 7 3 4 1 3 8 4 2 3]
 [1 5 2 4 2 7 1 0 5 5 4 2 3]
 [4 4 7 3 3 2 5 3 0 0 8 1 7]
 [3 4 0 1 1 7 2 4 0 8 6 2 6]
 [7 5 8 1 4 8 3 2 7 4 7 0 6]
 [1 8 4 4 6 0 5 3 2 0 2 4 1]
 [4 3 6 7 4 2 3 8 2 8 8 2 0]
 [5 7 5 6 4 3 0 6 5 5 7 6 4]]


In [3]:
print(x0[0]) #row

[0 5 0 3 6 8 1 0 5 7 0 8 5]


In [4]:
print(x0[:,0]) #column
print(x0.T[0]) #column

[0 3 2 6 6 1 4 3 7 1 4 5]
[0 3 2 6 6 1 4 3 7 1 4 5]


In [5]:
num_rows = (len(x0))
num_columns = (len(x0[0]))
print("x0 is a "+str(num_rows)+"x"+str(num_columns)+" matrix")

x0 is a 12x13 matrix


In [6]:
x1 = np.array([[x0[0][0], x0[0][1]],[x0[1][0], x0[1][1]]]) # 'bigram'
print(x1)

[[0 5]
 [3 6]]


In [7]:
'''Moves down the matrix from upper left corner'''

def matrixNgram(matrix, n):
    num_rows = (len(matrix))
    num_columns = (len(matrix[0]))
    print(str(num_rows)+"x"+str(num_columns)+" matrix")
    for i in range(0, num_rows):
        print("Row " + str(i))
        temp_list_of_rows = []
        
        gram_rows = np.array(matrix[i:(i+n)]) #make matricies with sliding window of 3 rows
        if len(gram_rows) == n:
#             print(gram_rows)
#             print("------")

            for j in range(0, n): #shorten num of gram_row columns to n, 
                temp_row = gram_rows[j][:n]
                temp_list_of_rows.append(temp_row)
                
            gram = np.array(temp_list_of_rows)
            print(gram)
            print("-------------")
        if len(gram_rows) < n:
            print("not enough rows to compute")

            

print(x0)
matrixNgram(x0, 4)    

[[0 5 0 3 6 8 1 0 5 7 0 8 5]
 [3 6 5 0 6 7 7 1 6 2 2 2 2]
 [2 2 5 6 4 2 7 1 8 8 6 8 1]
 [6 3 7 4 4 3 1 4 5 6 0 3 4]
 [6 6 0 8 7 3 4 1 3 8 4 2 3]
 [1 5 2 4 2 7 1 0 5 5 4 2 3]
 [4 4 7 3 3 2 5 3 0 0 8 1 7]
 [3 4 0 1 1 7 2 4 0 8 6 2 6]
 [7 5 8 1 4 8 3 2 7 4 7 0 6]
 [1 8 4 4 6 0 5 3 2 0 2 4 1]
 [4 3 6 7 4 2 3 8 2 8 8 2 0]
 [5 7 5 6 4 3 0 6 5 5 7 6 4]]
12x13 matrix
Row 0
[[0 5 0 3]
 [3 6 5 0]
 [2 2 5 6]
 [6 3 7 4]]
-------------
Row 1
[[3 6 5 0]
 [2 2 5 6]
 [6 3 7 4]
 [6 6 0 8]]
-------------
Row 2
[[2 2 5 6]
 [6 3 7 4]
 [6 6 0 8]
 [1 5 2 4]]
-------------
Row 3
[[6 3 7 4]
 [6 6 0 8]
 [1 5 2 4]
 [4 4 7 3]]
-------------
Row 4
[[6 6 0 8]
 [1 5 2 4]
 [4 4 7 3]
 [3 4 0 1]]
-------------
Row 5
[[1 5 2 4]
 [4 4 7 3]
 [3 4 0 1]
 [7 5 8 1]]
-------------
Row 6
[[4 4 7 3]
 [3 4 0 1]
 [7 5 8 1]
 [1 8 4 4]]
-------------
Row 7
[[3 4 0 1]
 [7 5 8 1]
 [1 8 4 4]
 [4 3 6 7]]
-------------
Row 8
[[7 5 8 1]
 [1 8 4 4]
 [4 3 6 7]
 [5 7 5 6]]
-------------
Row 9
not enough rows to compute
Row 10
not enough ro

In [8]:
'''Moves diagonally accross the matrix'''

def matrixNgram2(matrix, n):
    num_rows = (len(matrix))
    num_columns = (len(matrix[0]))
    print(str(num_rows)+"x"+str(num_columns)+" matrix")
    

    c = 0
    for i in range(0, num_rows):
        print("Row " + str(i))
        start_nw = []
        
        west_rows = np.array(matrix[i:(i+n)]) #make running matricies with sliding window of n rows
        if len(west_rows) == n:
#             print(west_rows)
#             print("------")

            for j in range(0, n): #shorten num of gram_row columns to
                
#                 if n+c > num_columns:
#                     print("ran out of columns")
                    
                temp_row = west_rows[j][c:n+c] #shift columns over each time to move diagonal, with n-gram window
                start_nw.append(temp_row)
                
            start_gram = np.array(start_nw)
            print(start_gram)
            print("-------------")
        if len(west_rows) < n:
            print("not enough rows to compute")
        
        c +=1

print(x0)
matrixNgram2(x0, 4)

[[0 5 0 3 6 8 1 0 5 7 0 8 5]
 [3 6 5 0 6 7 7 1 6 2 2 2 2]
 [2 2 5 6 4 2 7 1 8 8 6 8 1]
 [6 3 7 4 4 3 1 4 5 6 0 3 4]
 [6 6 0 8 7 3 4 1 3 8 4 2 3]
 [1 5 2 4 2 7 1 0 5 5 4 2 3]
 [4 4 7 3 3 2 5 3 0 0 8 1 7]
 [3 4 0 1 1 7 2 4 0 8 6 2 6]
 [7 5 8 1 4 8 3 2 7 4 7 0 6]
 [1 8 4 4 6 0 5 3 2 0 2 4 1]
 [4 3 6 7 4 2 3 8 2 8 8 2 0]
 [5 7 5 6 4 3 0 6 5 5 7 6 4]]
12x13 matrix
Row 0
[[0 5 0 3]
 [3 6 5 0]
 [2 2 5 6]
 [6 3 7 4]]
-------------
Row 1
[[6 5 0 6]
 [2 5 6 4]
 [3 7 4 4]
 [6 0 8 7]]
-------------
Row 2
[[5 6 4 2]
 [7 4 4 3]
 [0 8 7 3]
 [2 4 2 7]]
-------------
Row 3
[[4 4 3 1]
 [8 7 3 4]
 [4 2 7 1]
 [3 3 2 5]]
-------------
Row 4
[[7 3 4 1]
 [2 7 1 0]
 [3 2 5 3]
 [1 7 2 4]]
-------------
Row 5
[[7 1 0 5]
 [2 5 3 0]
 [7 2 4 0]
 [8 3 2 7]]
-------------
Row 6
[[5 3 0 0]
 [2 4 0 8]
 [3 2 7 4]
 [5 3 2 0]]
-------------
Row 7
[[4 0 8 6]
 [2 7 4 7]
 [3 2 0 2]
 [8 2 8 8]]
-------------
Row 8
[[7 4 7 0]
 [2 0 2 4]
 [2 8 8 2]
 [5 5 7 6]]
-------------
Row 9
not enough rows to compute
Row 10
not enough ro